Vagrant::Config.run do |config|
  config.vm.box = "dev-vm-2.0"
  config.vm.box_url = "http://zeelot.s3.amazonaws.com/dev-vm-2.0-base.box"

  # Boot with a GUI so you can see the screen. (Default is headless)
  # config.vm.boot_mode = :gui

  config.vm.network :hostonly, "33.33.33.30"

  # HTTP
  # config.vm.forward_port(80, 80)
  config.vm.share_folder("app", "/home/vagrant/app", "../")

  config.vm.provision :chef_solo do |chef|
    # This path will be expanded relative to the project directory
    chef.cookbooks_path = "cookbooks"

    chef.add_recipe("dev-vm")
  end
end
